version: '3'

services:

  nginx:
    image: nginx:1.17.10
    container_name: nginx-czhub
    depends_on:
        - frontend
        - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
    depends_on:
        - backend
    ports:
      - 5001:5001
    restart: on-failure

  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
    ports:
      - 5002:5002
    restart: on-failure
