version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    depends_on:
        - frontend
        - backend
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
    depends_on:
        - backend
    ports:
      - 8080:80
    restart: on-failure

  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
    ports:
      - 5002:5002
    restart: on-failure
